server:
  port: 8380
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: reader-service
aspect:
  enabled: true
  timer-switcher: true
  log-level: WARN